#Antal poster per lärosäte på modsnivån
PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#>

SELECT xsd:string(?_orgCode) COUNT(?_orgCode) as ?c
WHERE
{
{
SELECT DISTINCT ?_orgCode ?Mods
{

?Mods a mods_m:Mods .
?Mods mods_m:recordContentSourceValue ?_orgCode .
}
}
}
GROUP BY ?_orgCode
ORDER BY ?_orgCode
