#Antal poster per lärosäte
PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#>
SELECT
 xsd:string(?_orgCode), COUNT(xsd:string(?_orgCode))
{
?Record mods_m:hasMods ?Mods .
    ?Mods a mods_m:Mods .
?Mods mods_m:recordContentSourceValue ?_orgCode .
}
GROUP BY xsd:string(?_orgCode)
