# Listar alla lärosäten som har något fel av typen "Multiple Variants of Name" och hur fördelningen är över antalet namnformer
PREFIX xlink: <http://www.w3.org/1999/xlink#> 
PREFIX mods_m: <http://swepub.kb.se/mods/model#>
PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
SELECT ?_authority ?variantCount count(?variantCount)

WHERE{
{
SELECT DISTINCT
?_href ?_authority
count(distinct ?_nameNorm ) as ?variantCount
WHERE
{
?Record a mods_m:Record .
?Record mods_m:hasMods ?Mods .
?Mods mods_m:hasName ?Name .
?Name a mods_m:Name .
?Name xlink:href ?_href .
?Name mods_m:authority ?_authority .
?Name mods_m:nameValueNormalized ?_nameNorm .

#FILTER ( xsd:string(?_authority) IN ( 'su' ) ) 
# FILTER ( xsd:string(?_href) NOT IN ( 'n / a' ) ) # Om det är något värde ni vill undanhålla från resultatet

MINUS
{
?Violation a swpa_m:HREFViolation .
?Violation swpa_m:relatedRecord ?Record .
}

}
GROUP BY ?_authority ?_href 
HAVING ( count(distinct ?_nameNorm ) > 1)
ORDER BY DESC(count(distinct ?_nameNorm ) )
}
}GROUP BY ?_authority ?variantCount 
ORDER BY ?_authority (count(?variantCount))
