#IDENTIFIERING AV DUBBLETTER VID UTTAG FRÅN ORIGINALDATA

#Lista av alla möjliga dubbletter för varje post, både lokala och nationella.
#PossiblySameAs relation mellan poster med total match vikt > 1 , utan hänsyn till brister:

PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#> 
PREFIX xlink: <http://www.w3.org/1999/xlink#> 
SELECT DISTINCT?_recordID
?_dubblettID
WHERE
{
?Record a mods_m:Record .
?Record mods_m:hasMods ?Mods .
?Mods a mods_m:Mods .
?Mods mods_m:identifierValue ?_recordID .
?Record swpa_m:possiblySameAs ?Dubblett .
?Dubblett mods_m:hasMods ?Mods2 .
?Mods2 mods_m:identifierValue ?_dubblettID .
}
ORDER BY ?_recordID
