#Alternativt utifrån uttag via publikationslista 
#Lägg till fälten i grönt i sökfrågan baserad på uttag för publikationslistan för en viss forskare samt filtrera med forskaren i rött:
PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#> 
PREFIX xlink: <http://www.w3.org/1999/xlink#> 
SELECT DISTINCT?_name
?_orcid
?_titleValue
?_orgCode
?_pubYear
?_publicatType
?_channel
?_subject
?_issn
?_isbn
?_publisher
?_place
?_volume
?_issue
?_startPage
?_endPage
?_recordID
WHERE
{
?Record a mods_m:Record .
?Mods a mods_m:Mods .
?Mods mods_m:identifierValue ?_recordID .
?Mods mods_m:hasTitleInfo ?TitleInfo .
MINUS { ?TitleInfo mods_m:type 'alternative'^^xsd:string }
?TitleInfo mods_m:hasTitle ?Title .
?Title mods_m:titleValue ?_titleValue .
#START_<?_isbn>
OPTIONAL
{ 
?Mods mods_m:hasIdentifier ?ISBN .
?ISBN mods_m:isbnValue ?_isbn .
} 
#END_<?_isbn>

#START_<?_channel>
OPTIONAL { ?Mods swpa_m:titleValueRelatedItem ?_channel }
#END_<?_channel>
#START_<?_issn>
OPTIONAL { ?Mods swpa_m:issnRelatedItem ?_issn }
#END_<?_issn>

?Mods a mods_m:Mods .
?Mods mods_m:hasRelatedItem ?RelatedItem .
?RelatedItem mods_m:hasPart ?Part .

# Publisher
?Mods mods_m:hasOriginInfo ?OriginInfo .
OPTIONAL
{
?OriginInfo mods_m:hasPublisher ?Publisher .
?Publisher mods_m:publisherValue ?_publisher .
}
#Place
OPTIONAL
{
?OriginInfo mods_m:hasPlace ?Place .
?Place mods_m:hasPlaceTerm ?PlaceTerm .
?PlaceTerm mods_m:placeTermValue ?_place .
}

#Sidor
OPTIONAL
{
?Part mods_m:hasExtent ?Extent .
?Extent mods_m:hasStart ?StartP .
?StartP a mods_m:Start .
?StartP mods_m:startValue ?_startPage .
?Extent mods_m:hasEnd ?EndP .
?EndP a mods_m:End .
?EndP mods_m:endValue ?_endPage.
}
#Volume
OPTIONAL
{
?Part mods_m:hasDetail ?Detail1 .
?Detail1 mods_m:hasNumber ?Number1 .
?Number1 mods_m:numberValue ?_volume .
?Detail1 mods_m:type "volume"^^xsd:string .
}

#Issue
OPTIONAL
{
?Part mods_m:hasDetail ?Detail2 .
?Detail2 mods_m:hasNumber ?Number2 .
?Number2 mods_m:numberValue ?_issue .
?Detail2 mods_m:type "issue"^^xsd:string .
}

{
SELECT DISTINCT ?Record ?Mods ?_pubYear ?_orgCode ?_publicatType ?_hsv3 ?_subject ?_OA ?Name ?_name ?_orcid
WHERE
{
?Record mods_m:hasMods ?Mods .
?Record a mods_m:Record .
?Mods a mods_m:Mods .
?Mods swpa_m:publicationYear ?_pubYear .
?Mods mods_m:recordContentSourceValue ?_orgCode .
?Mods swpa_m:publicationTypeCode ?_publicatType .
?Record swpa_m:isPublished ?_isPublished .
OPTIONAL { ?Mods swpa_m:oaType ?_OA }
?Mods mods_m:hasName ?Name . 
#START_<?_name>
?Name foaf:name ?_name .
#END_<?_name>

OPTIONAL
{ 
?Mods mods_m:hasSubject ?Subject .
?Subject swpa_m:hsv3 ?_hsv3 .
GRAPH <http://www.ub.uu.se/epub/categories/hsv#graph> 
{ 
?Class a owl:Class . 
}
?Class swpa_m:id ?_hsv3  . 
?Class rdfs:label ?_subject . 
?Class swpa_m:level "3"^^xsd:integer . 
FILTER ( lang(?_subject) = 'sv') 
}
?Mods mods_m:hasName ?Name . 
?Name foaf:name ?_name .
FILTER ( bif:contains(?_name, '"drake" AND "isabel"' ) )
OPTIONAL { ?Name swpa_m:orcid ?_orcid }
FILTER ( ?_isPublished = 1 ) 
}
LIMIT 500
}
}
LIMIT 100
