#Same RelatedItem match – not in Publication Channel
CONSTRUCT
{
?uriMatch a swpa_m:RelatedItemMatch .
?Mods1 swpa_m:hasMatch ?uriMatch .
?uriMatch swpa_m:hasTarget ?Mods2 .
?uriMatch swpa_m:compares ?TitleInfo1 .
?uriMatch swpa_m:compares ?TitleInfo2 .
?uriMatch swpa_m:weight “0.05”^^xsd:float .
}
WHERE
{{
SELECT DISTINCT
bif:sprintf_iri(‘http://swepub.kb.se/SwePubAnalysis/data#RelatedItemMatch__%s’, bif:substring(sql:localName( ?Mods1),9,1000)) as ?uriMatch
?Mods1 ?Mods2 ?TitleInfo1 ?TitleInfo2
WHERE
{
# Exclude records mapped directly to Channel list
MINUS { ?Mods1 swpa_m:publishedIn ?Journal1 }
MINUS { ?Mods2 swpa_m:publishedIn ?Journal2 }{
SELECT DISTINCT ?Mods1 ?TitleInfo1 ?TitleInfo2 ?Mods2
WHERE
{{
SELECT DISTINCT ?Mods1 ?Mods2 ?g1 ?g2 ?TitleInfo1 ?TitleInfo2
WHERE
{
#Must have a match already
?Mods1 swpa_m:hasMatch ?Match .
?Match swpa_m:hasTarget ?Mods2 .
GRAPH ?g1
{
?Mods1 a mods_m:Mods .
?Mods1 mods_m:hasRelatedItem ?RelatedItem1 .
?RelatedItem1 mods_m:hasTitleInfo ?TitleInfo1 .
}
GRAPH ?g2
{
?Mods2 a mods_m:Mods .
?Mods2 mods_m:hasRelatedItem ?RelatedItem2 .
?RelatedItem2 mods_m:hasTitleInfo ?TitleInfo2 .
}
}
}GRAPH ?g1
{
?TitleInfo1 mods_m:hasTitle ?Title1 .
?Title1 mods_m:titleValue ?_titleValue .
}GRAPH ?g
{
?TitleInfo2 mods_m:hasTitle ?Title2 .
?Title2 mods_m:titleValue ?_titleValue .
}}
}}
}
}
