# Same Alternative Title match
CONSTRUCT
{
?uriMatch a swpa_m:AlternativeTitleMatch .
?Mods1 swpa_m:hasMatch ?uriMatch .
?uriMatch swpa_m:hasTarget ?Mods2 .
?uriMatch swpa_m:compares ?Title1 .
?uriMatch swpa_m:compares ?Title2 .
?uriMatch swpa_m:weight ?weight
}
WHERE
{
{
SELECT
bif:sprintf_iri(‘http://swepub.kb.se/SwePubAnalysis/data#AlternativeTitleMatch__%s’, ?localid) as ?uriMatch
?Mods1 ?Mods2 ?Title1 ?Title2
bif:__min(xsd:float(strlen(?titlevalue)) / 100.0, 0.5) as ?weightWHERE
{
FILTER( ?Mods1 != ?Mods2 )?Mods1 mods_m:hasTitleInfo ?TitleInfo1 .
?Mods1 a mods_m:Mods .
?Mods1 swpa_m:localID ?localid .
?TitleInfo1 a mods_m:TitleInfo .
?TitleInfo1 mods_m:type ‘alternative’^^xsd:string .
?TitleInfo1 mods_m:hasTitle ?Title1 .
?Title1 mods_m:titleValueNormalized ?titlevalue .?Mods2 mods_m:hasTitleInfo ?TitleInfo2 .
?Mods2 a mods_m:Mods .
?TitleInfo2 a mods_m:TitleInfo .
?TitleInfo2 mods_m:type ‘alternative’^^xsd:string .
?TitleInfo2 mods_m:hasTitle ?Title2 .
?Title2 mods_m:titleValueNormalized ?titlevalue .FILTER ( strlen( ?titlevalue) > 15 )
}
}
}
