#SamePublicationAs and SameCreativeWork without relatedItem
CONSTRUCT
{
?Record1 swpa_m:samePublicationAs ?Record2 .
?Record1 swpa_m:sameCreativeWorkAs ?Record2 .
}
WHERE
{
SELECT
?Record1
?Record2
sum( ?_weight ) as ?totalweight
WHERE
{
?Record1 mods_m:hasMods ?Mods1 .
?Record1 a swpa_m:DeduplicationEligible .
?Record2 mods_m:hasMods ?Mods2 .
?Record2 a swpa_m:DeduplicationEligible .# Have no relatedItem
MINUS
{
?Mods1 mods_m:hasRelatedItem ?RelatedItem .
}# exclude white listed
MINUS
{
?WhiteListed a swpa_m:CreativeWorkInstanceDuplicateAdjudication .
?WhiteListed swpa_m:isDuplicate 0 .
?WhiteListed swpa_m:compares ?Record1 .
?WhiteListed swpa_m:compares ?Record2 .
}
{
SELECT DISTINCT
?Mods1
?Match
?_weight
WHERE
{
?Mods1 a mods_m:Mods .
?Mods1 swpa_m:hasMatch ?Match .
?Match swpa_m:weight ?_weight .
}
}
?Match swpa_m:hasTarget ?Mods2 .
}
GROUP BY ?Record1 ?Record2
HAVING ( sum( xsd:float(?_weight) ) > 1)
}
