PREFIX swpa_m: <http://swepub.kb.se/SwePubAnalysis/model#>
PREFIX mods_m: <http://swepub.kb.se/mods/model#>
PREFIX outt_m: <http://swepub.kb.se/SwePubAnalysis/OutputTypes/model#>
PREFIX xlink: <http://www.w3.org/1999/xlink#> 
SELECT ?_pubYear COUNT(DISTINCT ?_recordID) 
WHERE
{
?Record a mods_m:Record .
?Mods a mods_m:Mods .

?Mods mods_m:identifierValue ?_recordID .

{
SELECT DISTINCT ?Record ?Mods ?_pubYear ?_orgCode ?_publicatType ?_outputCode ?_contentType ?_hsv1 ?_hsv3 ?_hsv5 ?_OA ?_name ?_localID ?_orcid ?_affiliation
WHERE
{
?Record mods_m:hasMods ?Mods .
?Record a mods_m:Record .
?Mods a mods_m:Mods .

?Mods swpa_m:publicationYear ?_pubYear .
?Mods mods_m:recordContentSourceValue ?_orgCode .
?Record swpa_m:hasOutputType ?OutputType .
?OutputType outt_m:code ?_outputCode .
?Mods swpa_m:publicationTypeCode ?_publicatType .
?Mods swpa_m:contentTypeCode ?_contentType .
?Record swpa_m:isPublished ?_isPublished .
?Mods mods_m:hasName ?Name .
?Mods swpa_m:oaType ?_OA #If all
#Mods swpa_m:oaType "green"^^<http://www.w3.org/2001/XMLSchema#string> # If Green
#?Mods swpa_m:oaType "gold"^^<http://www.w3.org/2001/XMLSchema#string> #If Gold
FILTER ( ?_pubYear >= 2010 ) 
FILTER ( ?_pubYear <= 2015 ) 

#FILTER ( ?_isPublished = 1 ) 

#FILTER ( BOUND(?_OA )) # If all

}
LIMIT 10000000
}
}
GROUP By ?_pubYear
order by ?_pubYear
LIMIT 10000000
