#Same Author Name match
PREFIX NQUADS: <keep_loop>
SELECT DISTINCT ?year ?site ?pubType
WHERE
{
?Mods a mods_m:Mods .
?Mods swpa_m:publicationYear ?year .
?Mods mods_m:recordContentSourceValue ?site .
?Mods swpa_m:publicationTypeCode ?pubType .
}
ORDER BY DESC(?year) ?site#LOOPCONSTRUCT
{
?uriMatch a swpa_m:AuthorNameMatch .
?Mods1 swpa_m:hasMatch ?uriMatch .
?uriMatch swpa_m:hasTarget ?Mods2 .
?uriMatch swpa_m:compares ?Name1 .
?uriMatch swpa_m:compares ?Name2 .
?uriMatch swpa_m:weight ?weight .
}
WHERE
{
{
SELECT DISTINCT
bif:sprintf_iri(‘http://swepub.kb.se/SwePubAnalysis/data#AuthorNameMatch__%s’, bif:substring(sql:localName( ?Name1),7,1000)) as ?uriMatch
?Mods1 ?Mods2 ?Name1 ?Name2
xsd:float( 0.15 / xsd:float(?creatorCount) ) as ?weight
WHERE
{
{
SELECT DISTINCT ?Mods1 ?Mods2 ?Name1 ?Name2 ?creatorCount
WHERE
{
{
SELECT DISTINCT ?Mods1 ?Mods2
WHERE
{
?Mods1 swpa_m:publicationYear <?year> .
?Mods1 mods_m:recordContentSourceValue <?site> .
?Mods1 swpa_m:publicationTypeCode <?pubType> .
?Mods1 swpa_m:hasMatch ?Match .
?Match swpa_m:hasTarget ?Mods2 .
}
}?Mods1 mods_m:hasName ?Name1 .
?Name1 mods_m:nameValueNormalized ?normname .?Mods2 mods_m:hasName ?Name2 .
?Name2 mods_m:nameValueNormalized ?normname .MINUS
{
?Mods1 swpa_m:hasMatch ?matchAuthorID .
?matchAuthorID a swpa_m:AuthorLocalIDMatch .
}
?Mods1 swpa_m:creatorCount ?creatorCount .
}}}
}
}
