# Same ISBN match
CONSTRUCT
{
?uriMatch a swpa_m:ISBNIdentityMatch .
?Mods1 swpa_m:hasMatch ?uriMatch .
?uriMatch swpa_m:hasTarget ?Mods2 .
?uriMatch swpa_m:compares ?Identifier1 .
?uriMatch swpa_m:compares ?Identifier2 .
}
WHERE
{
{
SELECT DISTINCT
bif:sprintf_iri(‘http://swepub.kb.se/SwePubAnalysis/data#ISBNIdentityMatch__%s’, bif:substring(sql:localName( ?Identifier1),13,1000)) as ?uriMatch
?Mods1 ?Mods2 ?Identifier1 ?Identifier2
WHERE
{
FILTER( ?Mods1 != ?Mods2 )
?Mods1 mods_m:hasIdentifier ?Identifier1 .
?Mods1 a mods_m:Mods .
?Identifier1 a mods_m:Identifier .
?Identifier1 mods_m:isbnHyphens ?isbn .?Mods2 mods_m:hasIdentifier ?Identifier2 .
?Mods2 a mods_m:Mods .
?Identifier2 a mods_m:Identifier .
?Identifier2 mods_m:isbnHyphens ?isbn .
}}
}
